source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'PermissionManager_Example' do
#  pod 'KMPermissionManager', :subspecs => ['calendar'], :path => '../'
pod 'KMPermissionManager', :path => '../'

  target 'PermissionManager_Tests' do
    inherit! :search_paths

    
  end
end
