use_frameworks!

platform :ios, '8.0'

target 'PermissionManager_Example' do
  pod 'PermissionManager', :path => '../'

  target 'PermissionManager_Tests' do
    inherit! :search_paths

    
  end
end
